[package]
name = "noosphere-fs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noosphere = { path = "../noosphere" }
noosphere-storage = { path = "../noosphere-storage" }

tokio = { version = "^1", features = ["sync", "io-util"] }
tokio-util = { version = "~0.7", features = ["io"] }
tokio-stream = "~0.1"
async-stream = "~0.3"
bytes = "^1"
once_cell = "^1"
cid = "~0.8"
anyhow = "^1"

futures-util = "~0.3"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ucan = { version = "0.6.0-alpha.1", git = "https://github.com/cdata/rs-ucan.git" }
ucan-key-support = { version = "0.4.0-alpha.1", git = "https://github.com/cdata/rs-ucan.git" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
ucan = { version = "0.6.0-alpha.1", features = ["web"], git = "https://github.com/cdata/rs-ucan.git" }
ucan-key-support = { version = "0.4.0-alpha.1", features = ["web"], git = "https://github.com/cdata/rs-ucan.git" }